#!/usr/bin/env python3
"""Profile bundled SafeHeat local data without third-party packages."""
from __future__ import annotations

import csv
import hashlib
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw"
PROCESSED = ROOT / "data" / "processed"
JSON_OUT = PROCESSED / "local_data_profile.json"
MD_OUT = ROOT / "DATA_SHAPE_PROFILE.md"


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def scalar_type(value: str) -> str:
    value = value.strip()
    if value == "":
        return "empty"
    low = value.lower()
    if low in {"true", "false", "yes", "no"}:
        return "boolean_like"
    try:
        int(value)
        return "integer"
    except ValueError:
        pass
    try:
        float(value)
        return "number"
    except ValueError:
        pass
    if value.startswith("http://") or value.startswith("https://"):
        return "url"
    return "text"


def profile_csv(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)
        columns = reader.fieldnames or []
    fields = []
    for column in columns:
        values = [str(row.get(column, "")) for row in rows]
        nonempty = [v for v in values if v.strip()]
        types = sorted({scalar_type(v) for v in nonempty})
        distinct = len(set(nonempty))
        samples = []
        for value in nonempty:
            if value not in samples:
                samples.append(value)
            if len(samples) == 3:
                break
        fields.append({
            "name": column,
            "nonNullCount": len(nonempty),
            "nullCount": len(rows) - len(nonempty),
            "distinctNonNullCount": distinct,
            "observedTypes": types,
            "samples": samples,
        })
    return {
        "path": str(path.relative_to(ROOT)),
        "format": "csv",
        "bytes": path.stat().st_size,
        "sha256": sha256(path),
        "rowCount": len(rows),
        "columnCount": len(columns),
        "columns": fields,
    }


def json_type(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, int):
        return "integer"
    if isinstance(value, float):
        return "number"
    if isinstance(value, str):
        return "string"
    if isinstance(value, list):
        return "array"
    if isinstance(value, dict):
        return "object"
    return type(value).__name__


def profile_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    result: dict[str, Any] = {
        "path": str(path.relative_to(ROOT)),
        "format": "json",
        "bytes": path.stat().st_size,
        "sha256": sha256(path),
        "rootType": json_type(value),
    }
    if isinstance(value, dict):
        result["topLevelFields"] = [
            {"name": key, "type": json_type(val), "size": len(val) if isinstance(val, (list, dict, str)) else None}
            for key, val in value.items()
        ]
        if path.name == "demo_data.json":
            result["domainSections"] = {
                "sources": len(value.get("sources", [])),
                "facilities": len(value.get("facilities", [])),
                "zones": len(value.get("zones", [])),
                "partners": len(value.get("partners", [])),
                "tasks": len(value.get("tasks", [])),
                "auditEvents": len(value.get("auditEvents", [])),
            }
            for key in ("sources", "facilities", "zones", "partners", "tasks", "auditEvents"):
                items = value.get(key, [])
                field_union = sorted({field for item in items if isinstance(item, dict) for field in item})
                result.setdefault("sectionFieldUnions", {})[key] = field_union
    elif isinstance(value, list):
        result["rowCount"] = len(value)
        result["fieldUnion"] = sorted({field for item in value if isinstance(item, dict) for field in item})
    return result


def render_markdown(profile: dict[str, Any]) -> str:
    lines = [
        "# SafeHeat - Local Data Shape Profile",
        "",
        "**Generated:** 2026-07-19  ",
        "**Scope:** bundled raw/normalized research artifacts and the processed offline fixture",
        "",
        "This file is generated by `scripts/profile_local_data.py`. It profiles local shapes only; it does not establish event-time facility truth or replace the external API contracts in `API_ENDPOINTS.md`.",
        "",
        "## File summary",
        "",
        "| File | Format | Rows/sections | Columns/top-level fields | Bytes | SHA-256 |",
        "|---|---|---:|---:|---:|---|",
    ]
    for item in profile["files"]:
        if item["format"] == "csv":
            rows = item["rowCount"]
            columns = item["columnCount"]
        else:
            sections = item.get("domainSections")
            rows = ", ".join(f"{k}:{v}" for k, v in sections.items()) if sections else item.get("rowCount", "object")
            columns = len(item.get("topLevelFields", item.get("fieldUnion", [])))
        lines.append(f"| `{item['path']}` | {item['format']} | {rows} | {columns} | {item['bytes']} | `{item['sha256']}` |")

    for item in profile["files"]:
        lines.extend(["", f"## `{item['path']}`", ""])
        if item["format"] == "csv":
            lines.append(f"Rows: **{item['rowCount']}**. Columns: **{item['columnCount']}**.")
            lines.extend(["", "| Column | Non-null | Null | Distinct | Observed type(s) | Samples |", "|---|---:|---:|---:|---|---|"])
            for field in item["columns"]:
                samples = "; ".join(str(x).replace("|", "\\|")[:80] for x in field["samples"])
                types = ", ".join(field["observedTypes"]) or "empty"
                lines.append(f"| `{field['name']}` | {field['nonNullCount']} | {field['nullCount']} | {field['distinctNonNullCount']} | {types} | {samples} |")
        else:
            if "domainSections" in item:
                lines.append("Domain-section counts:")
                lines.append("")
                for key, count in item["domainSections"].items():
                    lines.append(f"- `{key}`: {count}")
                lines.extend(["", "Field unions by section:", ""])
                for key, fields in item.get("sectionFieldUnions", {}).items():
                    lines.append(f"- `{key}`: {', '.join(f'`{x}`' for x in fields) if fields else '(empty)' }")
            else:
                lines.append("Top-level fields:")
                lines.append("")
                for field in item.get("topLevelFields", []):
                    size = f", size {field['size']}" if field.get("size") is not None else ""
                    lines.append(f"- `{field['name']}`: {field['type']}{size}")
    lines.extend([
        "",
        "## Interpretation rules",
        "",
        "- Empty/null profiling describes the bundled snapshot, not a quality guarantee for future API responses.",
        "- URL, number, and boolean-like types are observed string forms in CSV and still require explicit parsing/validation.",
        "- Complete library/recreation normalized snapshots are research artifacts; the exact raw API response should be refreshed with the fetch script when needed.",
        "- The processed fixture is the complete runtime contract. Public-source data and synthetic operational status remain distinguishable inside it.",
        "- No profile result establishes that a facility is currently open or available.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    files = []
    for path in sorted(RAW.iterdir()):
        if path.is_file() and path.suffix.lower() == ".csv":
            files.append(profile_csv(path))
        elif path.is_file() and path.suffix.lower() == ".json":
            files.append(profile_json(path))
    files.append(profile_json(PROCESSED / "demo_data.json"))
    profile = {
        "schemaVersion": 1,
        "generatedDate": "2026-07-19",
        "root": "brainstorm/municipal/02-safeheat",
        "files": files,
    }
    JSON_OUT.write_text(json.dumps(profile, indent=2) + "\n", encoding="utf-8")
    MD_OUT.write_text(render_markdown(profile), encoding="utf-8")
    print(f"Wrote {JSON_OUT}")
    print(f"Wrote {MD_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
