#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";

const checks = [];

function commandVersion(command, args = ["--version"]) {
  let result = spawnSync(command, args, { encoding: "utf8" });
  if (result.status !== 0 && process.platform === "win32") {
    result = spawnSync([command, ...args].join(" "), { encoding: "utf8", shell: true });
  }
  if (result.status !== 0) return undefined;
  return (result.stdout || result.stderr).trim().split("\n")[0];
}

function add(name, ok, detail, required = true) {
  checks.push({ name, ok, detail, required });
}

const nodeMajor = Number(process.versions.node.split(".")[0]);
add(
  "Node.js",
  nodeMajor >= 24,
  nodeMajor === 24
    ? `v${process.versions.node}; matches the deployment runtime line`
    : `v${process.versions.node}; local runtime is newer, deployment remains pinned to Node 24`,
);

const npm =
  commandVersion(process.platform === "win32" ? "npm.cmd" : "npm") ??
  process.env.npm_config_user_agent?.split(" ")[0];
add("npm", Boolean(npm), npm ?? "not found");

const git = commandVersion("git");
add("git", Boolean(git), git ?? "not found");

const docker = commandVersion("docker");
add("Docker", Boolean(docker), docker ?? "optional; not found", false);

const firebaseBinary =
  process.platform === "win32" ? "node_modules/.bin/firebase.cmd" : "node_modules/.bin/firebase";
const firebase = existsSync(firebaseBinary) ? commandVersion(firebaseBinary) : undefined;
add("Firebase CLI", Boolean(firebase), firebase ?? "installed after npm install", false);

add(
  "Local environment",
  existsSync(".env.local"),
  existsSync(".env.local") ? ".env.local found" : "copy .env.example to .env.local",
  false,
);
add(
  "Dependencies",
  existsSync("node_modules"),
  existsSync("node_modules") ? "node_modules found" : "run npm install",
  false,
);
add(
  "Lockfile",
  existsSync("package-lock.json"),
  existsSync("package-lock.json")
    ? "package-lock.json found"
    : "required for App Hosting; generated by first npm install",
  false,
);

const width = Math.max(...checks.map((check) => check.name.length));
for (const check of checks) {
  const mark = check.ok ? "PASS" : check.required ? "FAIL" : "NOTE";
  console.log(`${mark.padEnd(4)}  ${check.name.padEnd(width)}  ${check.detail}`);
}

const failed = checks.filter((check) => check.required && !check.ok);
if (failed.length > 0) {
  console.error(`\n${failed.length} required check(s) failed.`);
  process.exit(1);
}

console.log("\nRequired tooling is ready.");
